version: '3.0'
services:
  db:
    container_name: mysqldb
    image: 'mysql:8'
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./database/mysql/data:/var/lib/mysql:rw
    env_file:
      - db.env
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    ports:
      - "8580:80"
    links:
      - db
    env_file: 
      - db.env

  mongo:
    container_name: mongodb
    image: mongo
    restart: always
    env_file: 
      - db.env
    ports:
      - 27017:27017
    volumes:
      - ./database/mongodb/data:/data/db:rw

  mongo-express:
    container_name: mongo_client
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - mongo
    links:
      - mongo
    env_file: 
      - db.env
  redis:
    container_name: redis-server
    image: "redis:alpine"
    ports: 
      - 6379:6379
    volumes: 
      - ./redis-data:/var/lib/redis
    environment: 
      - REDIS_REPLICATION_MODE=master
  member-service:
    build: 
      context: ./images/nodejs
      dockerfile: Dockerfile
    container_name: member-service
    volumes: 
      - ./apps/member-service:/app
    working_dir: /app
    command: sh -c "npm install && npm run dev"
    environment:
      NODE_ENV: development
    ports: 
      - 3001:3000

  otp-service:
    build: 
      context: ./images/nodejs
      dockerfile: Dockerfile
    container_name: otp-service
    volumes: 
      - ./apps/otp-service:/app
    working_dir: /app
    command: sh -c "npm install && npm run dev"
    environment:
      NODE_ENV: development
    ports: 
      - 3002:3131