version: '3.0'
services:
  db:
    container_name: mysqldb
    image: 'mysql:8'
    restart: always
    ports:
      - "3306:3306"
    networks:
      - dbs-network
    volumes:
      - ./database/mysql/data:/var/lib/mysql
    env_file:
      - .env
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    ports:
      - "8580:80"
    links:
      - db
    networks:
      - dbs-network
    env_file: 
      - .env

  mongo:
    container_name: mongodb
    image: mongo
    restart: always
    env_file: 
      - .env
    ports:
      - 27017:27017
    expose:
      - 27017
    networks:
      - dbs-network
    volumes:
      - ./database/mongodb/data:/data/db

  mongo-express:
    container_name: mongo_client
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    env_file: 
      - .env
    networks:
      - dbs-network
  redis:
    container_name: redis-server
    image: "redis:alpine"
    command: redis-server --requirepass sOmE_sEcUrE_pAsS
    ports: 
      - 6379:6379
    volumes: 
      - ./redis-data:/var/lib/redis
    environment: 
      - REDIS_REPLICATION_MODE=master
    networks:
      - dbs-network

networks:
  dbs-network: